-- 2022-09-16
ALTER TABLE Users ADD pick_up_place VARCHAR(60);

-- 2022-09-17
ALTER TABLE Participant ADD status VARCHAR(30);

-- 2022-09-19
CREATE TABLE Bib_Number_seq (
    id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    activity_id INT(8) UNSIGNED NOT NULL,
    FOREIGN KEY (activity_id) REFERENCES Activity(id) ON DELETE CASCADE,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)